version: "3.8"

services:
  server:
    image: 10.8.0.1:5000/vinstp/downloader_bot_server:latest

    secrets:
      - source: downloader_bot_old_school_api_id
        target: /run/secrets/downloader_bot_old_school_api_id
      - source: downloader_bot_old_school_bot_token
        target: /run/secrets/downloader_bot_old_school_bot_token
      - source: downloader_bot_old_school_api_hash
        target: /run/secrets/downloader_bot_old_school_api_hash

    volumes:
        - "/mnt/oldschool/import:/media_from_dialogs"

    build:
      context: ./
      dockerfile: Dockerfile


secrets:
  downloader_bot_old_school_api_id:
    external: true
  downloader_bot_old_school_bot_token:
    external: true
  downloader_bot_old_school_api_hash:
      external: true
