version: "3.8"

services:
  server:

    volumes:
        - docker_old_school_volume:/mnt/oldschool

    build:
      context: ./
      dockerfile: Dockerfile

    restart: always
    
    
# Храним репозитории при перезапусках, чтобы не клонить каждый раз
volumes:
  docker_old_school_volume: